Saving the file to /tmp<br>
<pre>Converting image /tmp/outfile:
Loading and preparing image...
Generating color palette...
Reducing colors...
  5% 10% 15% 20% 25% 30% 35% 40% 45% 50% 55% 60% 65% 70% 75% 80% 85% 90% 95% 100% 
Splitting everything into square 128px sections...
Generating and saving terrain data (schematics)...
Saving image previews...
===================================================
Note: schematics are 130x130 in footprint, use their glass floor as a reference for map alignment.
Don't place any blocks touching the 128x128 map area, except for those the .schematic places there. Have fun.
</pre>Done! Check out the results <a href="./uploaded/1623155833/">HERE</a>. (Keep that link)<br><br>
